export type ProductFilterGroup =
  | "squishy"
  | "plush"
  | "bag-charms"
  | "diy-crafts"
  | "emotional-gifts"
  | "oem";

export type ProductImageSet = {
  hero: string;
  detail?: string;
  packaging?: string;
  oemCase?: string;
};

export type Product = {
  slug: string;
  name: string;
  category: string;
  tag: string;
  note: string;
  seoTitle?: string;
  seoDescription?: string;
  alt: string;
  keywords: string[];
  images: ProductImageSet;
  video?: string;
  featured?: boolean;
  bestseller?: boolean;
  availability?: "ready-stock";
  referenceSize?: string;
  filterGroup: ProductFilterGroup;
};

function images(slug: string, hero: string): ProductImageSet {
  return {
    hero,
    detail: `/images/products/${slug}/detail.png`,
    packaging: `/images/products/${slug}/packaging.png`,
    oemCase: `/images/products/${slug}/oem-case.png`,
  };
}

export const products: Product[] = [
  {
    slug: "ready-stock-highland-cow-tpr-squishy",
    name: "Ready Stock Highland Cow TPR Squishy Toy",
    category: "TPR Animal Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Highland cow TPR squeeze toy available in brown and orange colorways with a retail presentation box. Suitable for novelty stores, gift shops, impulse displays and bulk toy assortments. Request a live stock, unit-packing and carton check before ordering.",
    seoTitle: "Highland Cow TPR Squishy Toy Wholesale | Ready Stock",
    seoDescription: "Source ready-stock Highland cow TPR squishy toys in brown and orange colorways with retail-box presentation. Request live stock, carton packing and dispatch details.",
    alt: "ready stock brown and orange Highland cow TPR squishy toys wholesale",
    keywords: [
      "Highland cow squishy wholesale",
      "TPR cow squeeze toy",
      "cow stress toy bulk",
      "ready stock TPR squishy",
      "animal squishy toy supplier",
      "Highland cattle fidget toy",
    ],
    images: {
      hero: "/images/products/ready-stock-highland-cow-tpr-squishy/hero.png",
      packaging: "/images/products/ready-stock-highland-cow-tpr-squishy/packaging.png",
    },
    featured: true,
    bestseller: true,
    availability: "ready-stock",
    filterGroup: "squishy",
  },
  {
    slug: "squeaky-tongue-popping-animal-squishy",
    name: "Squeaky Tongue-Popping Animal Squishy Toy",
    category: "Squeaky Animal Squishy / Wholesale",
    tag: "Funny Squeeze Toy",
    note: "Funny animal squeeze toy with a tongue-popping action and built-in squeaker sound. Supplied in a colorful countertop display box with assorted animal designs for novelty stores, gift shops, party favors and bulk toy assortments.",
    seoTitle: "Squeaky Tongue-Popping Animal Squishy Toy Wholesale",
    seoDescription: "Wholesale squeaky tongue-popping animal squishy toys with funny squeeze action, BB squeaker sound, assorted animal designs and retail display-box packing.",
    alt: "squeaky tongue popping animal squishy toy wholesale display box",
    keywords: ["squeaky animal squishy toy", "tongue popping squeeze toy", "funny stress toy wholesale", "animal squeaker toy bulk"],
    images: {
      hero: "/images/products/squeaky-tongue-popping-animal-squishy/hero.webp",
      packaging: "/images/products/squeaky-tongue-popping-animal-squishy/display-box.png",
    },
    featured: true,
    filterGroup: "squishy",
  },

  {
    slug: "ready-stock-chocolate-bar-squishy",
    name: "Ready Stock Chocolate Bar Squishy",
    category: "Food Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Chocolate-bar squeeze toy in retail-ready packaging for novelty shops, gift stores, seasonal displays and bulk buyers. Ask us to confirm live quantity, unit packing, carton details and dispatch timing before ordering.",
    seoTitle: "Ready Stock Chocolate Bar Squishy Wholesale",
    seoDescription: "Source ready-stock chocolate bar squishy toys for wholesale novelty retail, gift stores and seasonal displays. Request a live stock, packing and dispatch check.",
    alt: "ready stock chocolate bar squishy squeeze toy wholesale retail packaging",
    keywords: ["chocolate bar squishy wholesale", "food squishy toy bulk", "ready stock squeeze toy", "chocolate stress toy supplier"],
    images: images("ready-stock-chocolate-bar-squishy", "/images/products/ready-stock-chocolate-bar-squishy/hero-20260815.webp"),
    featured: true,
    availability: "ready-stock",
    filterGroup: "squishy",
  },

  {
    slug: "ready-stock-halloween-butter-bar-squishy",
    name: "Ready Stock Halloween Butter Bar Squishy",
    category: "Halloween Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Halloween butter-bar squeeze toy in seasonal retail presentation for gift shops, party suppliers and bulk novelty assortments. Ask us to confirm current available quantity, unit packing, carton details and dispatch timing before ordering.",
    seoTitle: "Halloween Butter Bar Squishy Wholesale | Ready Stock",
    seoDescription: "Source Halloween butter bar squishy toys for wholesale seasonal retail, party favors and novelty assortments. Request a live stock, packing and dispatch check.",
    alt: "ready stock Halloween butter bar squishy squeeze toy wholesale retail display",
    keywords: ["Halloween butter squishy wholesale", "Halloween squeeze toy bulk", "seasonal squishy toys in stock", "Halloween party favor supplier"],
    images: images("ready-stock-halloween-butter-bar-squishy", "/images/products/ready-stock-halloween-butter-bar-squishy/hero.webp"),
    featured: true,
    availability: "ready-stock",
    filterGroup: "squishy",
  },
  {
    slug: "ready-stock-mango-squishy",
    name: "Ready Stock Mango Squishy",
    category: "Fruit Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Mango-shaped squeeze toy available for bulk wholesale orders. Reference size: 11.5 × 6 cm. Ask for current color availability, carton quantity and dispatch schedule.",
    seoTitle: "Ready Stock Mango Squishy Wholesale",
    seoDescription: "Wholesale ready-stock mango squishy toys for gift shops, novelty retail, party packs and bulk buyers. Ask for current stock and carton quantities.",
    alt: "ready stock mango squishy fruit squeeze toy wholesale 11.5 cm",
    keywords: ["mango squishy wholesale", "fruit squeeze toy bulk", "ready stock squishy toys", "mango stress toy supplier"],
    images: images("ready-stock-mango-squishy", "/images/products/ready-stock-mango-squishy/hero.png"),
    featured: true,
    bestseller: true,
    availability: "ready-stock",
    referenceSize: "11.5 × 6 cm",
    filterGroup: "squishy",
  },
  {
    slug: "ready-stock-giant-peach-squishy",
    name: "Ready Stock Giant Peach Squishy",
    category: "Jumbo Fruit Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Jumbo peach-shaped squishy for eye-catching novelty retail, seasonal gift displays and bulk purchase programs. Reference size: 17 × 15 cm. Contact us for live stock and packing details.",
    seoTitle: "Ready Stock Giant Peach Squishy Wholesale",
    seoDescription: "Buy jumbo peach squishy toys from ready stock for novelty retail, gift displays and bulk wholesale programs. Reference size 17 × 15 cm.",
    alt: "ready stock giant peach squishy wholesale jumbo fruit squeeze toy",
    keywords: ["giant peach squishy wholesale", "jumbo fruit squishy", "ready stock squeeze toy", "peach stress toy bulk"],
    images: images("ready-stock-giant-peach-squishy", "/images/products/ready-stock-giant-peach-squishy/hero.png"),
    featured: true,
    availability: "ready-stock",
    referenceSize: "17 × 15 cm",
    filterGroup: "squishy",
  },
  {
    slug: "ready-stock-cheese-cube-squishy",
    name: "Ready Stock Cheese Cube Squishy",
    category: "Novelty Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Boxed cheese-cube squeeze toy for countertop retail, gift packs and novelty-toy assortments. Reference product size: 12 × 12 × 12 cm. Ask for current stock quantity and outer-carton packing.",
    seoTitle: "Ready Stock Cheese Cube Squishy Wholesale",
    seoDescription: "Wholesale boxed cheese cube squishy toys from ready stock for novelty retail, gift packs and impulse displays. Reference size 12 cm.",
    alt: "ready stock cheese cube squishy boxed novelty squeeze toy wholesale",
    keywords: ["cheese cube squishy wholesale", "boxed novelty squeeze toy", "ready stock squishy toy", "cheese stress toy bulk"],
    images: images("ready-stock-cheese-cube-squishy", "/images/products/ready-stock-cheese-cube-squishy/hero.png"),
    featured: true,
    availability: "ready-stock",
    referenceSize: "12 × 12 × 12 cm",
    filterGroup: "squishy",
  },
  {
    slug: "ready-stock-giant-strawberry-squishy",
    name: "Ready Stock Giant Strawberry Squishy",
    category: "Jumbo Fruit Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Large strawberry squeeze toy available for wholesale novelty ranges, party gifts and retail displays. Reference size: 16 × 13 cm. Check current stock before placing a bulk order.",
    seoTitle: "Ready Stock Giant Strawberry Squishy Wholesale",
    seoDescription: "Wholesale ready-stock giant strawberry squishy toys for retail displays, party gifts and novelty assortments. Reference size 16 × 13 cm.",
    alt: "ready stock giant strawberry squishy wholesale fruit squeeze toy",
    keywords: ["giant strawberry squishy wholesale", "strawberry squeeze toy bulk", "ready stock fruit squishy", "jumbo stress toy supplier"],
    images: images("ready-stock-giant-strawberry-squishy", "/images/products/ready-stock-giant-strawberry-squishy/hero.png"),
    featured: true,
    availability: "ready-stock",
    referenceSize: "16 × 13 cm",
    filterGroup: "squishy",
  },
  {
    slug: "ready-stock-giant-banana-squishy",
    name: "Ready Stock Giant Banana Squishy",
    category: "Jumbo Fruit Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Oversized banana squeeze toy for novelty retail, party prizes and display-focused wholesale orders. Reference size: 35 × 7.5 cm. Ask for available stock, carton packing and dispatch timing.",
    seoTitle: "Ready Stock Giant Banana Squishy Wholesale",
    seoDescription: "Wholesale giant banana squishy toys from ready stock for novelty retail, party prizes and bulk gift programs. Reference size 35 cm.",
    alt: "ready stock giant banana squishy wholesale oversized fruit squeeze toy",
    keywords: ["giant banana squishy wholesale", "oversized banana squeeze toy", "ready stock novelty toys", "fruit stress toy bulk"],
    images: images("ready-stock-giant-banana-squishy", "/images/products/ready-stock-giant-banana-squishy/hero.png"),
    featured: true,
    availability: "ready-stock",
    referenceSize: "35 × 7.5 cm",
    filterGroup: "squishy",
  },
  {
    slug: "ready-stock-dragon-fruit-squishy",
    name: "Ready Stock Dragon Fruit Squishy",
    category: "Fruit Squishy / Wholesale",
    tag: "Ready Stock",
    note: "Dragon-fruit-shaped squeeze toy for colorful novelty retail, gift assortments and wholesale purchase. Reference size: 18.2 × 12 cm. Request a live stock check before ordering.",
    seoTitle: "Ready Stock Dragon Fruit Squishy Wholesale",
    seoDescription: "Wholesale ready-stock dragon fruit squishy toys for colorful novelty ranges, gift assortments and retail buyers. Reference size 18.2 × 12 cm.",
    alt: "ready stock dragon fruit squishy wholesale colorful fruit squeeze toy",
    keywords: ["dragon fruit squishy wholesale", "fruit squeeze toy ready stock", "novelty squishy bulk", "dragon fruit stress toy supplier"],
    images: images("ready-stock-dragon-fruit-squishy", "/images/products/ready-stock-dragon-fruit-squishy/hero.png"),
    featured: true,
    availability: "ready-stock",
    referenceSize: "18.2 × 12 cm",
    filterGroup: "squishy",
  },
  {
    slug: "dumpling-squishy-blind-box",
    name: "Custom Dumpling Squishy Blind Box Series",
    category: "Viral Squishy · OEM/ODM",
    tag: "2026 Trend Pick",
    note: "Pastel dumpling and bao bun squishies developed as blind-box assortments for collectible retail and social-commerce launches. Customize expressions, colorways, softness, scent, rarity mix and display packaging.",
    seoTitle: "Dumpling Squishy Blind Box Manufacturer",
    seoDescription: "Develop custom dumpling and bao bun squishy blind boxes with original expressions, color assortments, private-label packaging and OEM sampling.",
    alt: "custom dumpling squishy blind box bao bun sensory toys wholesale manufacturer",
    keywords: [
      "dumpling squishy manufacturer",
      "bao bun squishy wholesale",
      "squishy blind box OEM",
      "custom sensory toy supplier",
      "kawaii dumpling squishy",
      "private label squishy toys",
    ],
    images: images("dumpling-squishy-blind-box", "/images/products/dumpling-squishy-blind-box/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "transparent-gel-cube-squishy",
    name: "Custom Transparent Gel Cube Sensory Squishy",
    category: "Sensory Stress Cube · Wholesale",
    tag: "High Search Interest",
    note: "Clear rounded sensory cubes with colorful transparent finishes and optional glitter effects for tactile, desk and gift assortments. Customize dimensions, firmness, color, inclusions and retail packaging after material review.",
    seoTitle: "Transparent Gel Cube Squishy Manufacturer",
    seoDescription: "Source custom transparent gel cube squishies with buyer-specified firmness, colors, inclusions and private-label retail packaging.",
    alt: "custom transparent gel cube squishy sensory stress cube wholesale supplier",
    keywords: [
      "gel cube squishy",
      "sensory stress cube wholesale",
      "clear squishy cube manufacturer",
      "custom stress relief toys",
      "transparent sensory toy",
      "bulk squishy cubes",
    ],
    images: images("transparent-gel-cube-squishy", "/images/products/transparent-gel-cube-squishy/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "capybara-squishy-assortment",
    name: "Custom Capybara Squishy Assortment",
    category: "Character Squishy · OEM/ODM",
    tag: "Viral Character",
    note: "Original capybara squeeze characters with accessory variations for collectible assortments, impulse gifting and key retail moments. Customize poses, accessories, colors, material feel, packaging and assortment ratios.",
    seoTitle: "Capybara Squishy Wholesale & OEM Manufacturer",
    seoDescription: "Create original capybara squishy assortments with custom poses, accessories, colors, packaging and wholesale assortment planning.",
    alt: "custom capybara squishy stress toy assortment wholesale OEM manufacturer",
    keywords: [
      "capybara squishy",
      "capybara stress toy wholesale",
      "custom animal squishy manufacturer",
      "capybara sensory toy",
      "OEM character squishy",
      "bulk capybara toys",
    ],
    images: images("capybara-squishy-assortment", "/images/products/capybara-squishy-assortment/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "soft-sticky-squishy-assortment",
    name: "Custom Soft Sticky Squishy Assortment",
    category: "Taba-Style Squishy · OEM/ODM",
    tag: "Social Trend",
    note: "Ultra-soft fruit and animal squeeze shapes created for trend-led sensory collections. Develop original shapes with custom surface feel, color, print, firmness, dust-control packaging and private-label presentation.",
    seoTitle: "Soft Sticky Squishy OEM Manufacturer",
    seoDescription: "Develop original soft sticky squishy shapes with custom firmness, surface feel, printing, protective packaging and private-label presentation.",
    alt: "custom soft sticky taba style squishy assortment wholesale manufacturer",
    keywords: [
      "taba squishy manufacturer",
      "soft sticky squishy wholesale",
      "custom TPR squishy toy",
      "fruit squishy assortment",
      "private label sensory toys",
      "OEM soft squishy supplier",
    ],
    images: images("soft-sticky-squishy-assortment", "/images/products/soft-sticky-squishy-assortment/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "custom-tpr-popsicle-butter-cube-squishy",
    name: "Custom TPR Popsicle & Butter Cube Squishy Assortment",
    category: "TPR Fidget Toy / OEM-ODM",
    tag: "Colorful Sensory Assortment",
    note: "Colorful TPR squeeze toys in popsicle, butter cube, ice cream and novelty food-inspired shapes for sensory assortments, gift programs and impulse retail. Customize original shapes, transparent or marbled color effects, softness, logo, protective packaging and mixed-SKU display packs.",
    seoTitle: "Custom TPR Popsicle & Butter Cube Squishy Manufacturer",
    seoDescription: "Source custom TPR popsicle, butter cube and ice-cream-inspired squishy fidget toys with buyer-specified shapes, colors, softness, packaging and private-label options.",
    alt: "custom colorful TPR popsicle butter cube squishy fidget toy assortment manufacturer",
    keywords: [
      "TPR squishy fidget toy manufacturer",
      "popsicle squishy wholesale",
      "butter cube squeeze toy OEM",
      "ice cream stress toy bulk",
      "colorful sensory toy assortment",
      "custom TPR stress ball supplier",
    ],
    images: images(
      "custom-tpr-popsicle-butter-cube-squishy",
      "/images/products/custom-tpr-popsicle-butter-cube-squishy/hero.png",
    ),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "bakery-slow-rise-squishy-assortment",
    name: "Custom Bakery Slow-Rise Squishy Assortment",
    category: "Food Squishy · Wholesale",
    tag: "Evergreen Seller",
    note: "Croissant, toast, roll, waffle, cake and cream-bun slow-rise toys for food-themed retail and gift programs. Customize bakery shapes, recovery speed, scent, faces, colorways and branded packaging.",
    seoTitle: "Bakery Slow-Rise Squishy Wholesale Manufacturer",
    seoDescription: "Build custom bakery slow-rise squishy assortments with food shapes, recovery options, scent, face artwork and branded retail packaging.",
    alt: "custom bakery food slow rise squishy toys wholesale manufacturer",
    keywords: [
      "food squishy wholesale",
      "slow rise squishy manufacturer",
      "bread squishy toys bulk",
      "bakery squishy assortment",
      "scented squishy OEM",
      "custom dessert squishy",
    ],
    images: images("bakery-slow-rise-squishy-assortment", "/images/products/bakery-slow-rise-squishy-assortment/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "adult-desk-sensory-squishy",
    name: "Custom Adult Desk Sensory Squishy",
    category: "Quiet Desk Sensory · Private Label",
    tag: "Kidult Market",
    note: "Minimal pebble-shaped squeeze pieces designed for quiet desk, lifestyle gift and adult sensory collections. Customize form, resistance, color palette, surface finish, gift box and corporate branding without medical claims.",
    seoTitle: "Adult Desk Sensory Squishy Manufacturer",
    seoDescription: "Create private-label adult desk sensory squishies with custom resistance, shapes, color palettes, surface finish and corporate gift packaging.",
    alt: "custom adult desk sensory squishy quiet stress relief toy wholesale",
    keywords: [
      "adult stress relief toy",
      "quiet desk sensory toy",
      "custom desk squishy",
      "private label stress toys",
      "adult sensory product wholesale",
      "OEM squeeze toy manufacturer",
    ],
    images: images("adult-desk-sensory-squishy", "/images/products/adult-desk-sensory-squishy/hero.png"),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "custom-eva-geometric-cutout-squeeze-ball",
    name: "Custom EVA Geometric Cutout Squeeze Ball",
    category: "EVA Stress Ball / OEM-ODM",
    tag: "Color & Logo Custom",
    note: "Custom EVA squeeze balls with an original mix of rounded-triangle cutouts and diagonal slots for school gifts, party favors, promotional programs and sensory-toy assortments. Develop buyer-specified diameters, colorways, logo panels, individual packaging and display-ready mixed packs.",
    seoTitle: "Custom EVA Geometric Cutout Squeeze Ball Manufacturer",
    seoDescription: "Source custom EVA geometric cutout squeeze balls with buyer-specified size, color, logo panel and retail packaging for promotional gifts, party favors and sensory-toy programs.",
    alt: "custom colorful EVA geometric cutout squeeze ball sensory stress toy manufacturer",
    keywords: [
      "EVA squeeze ball manufacturer",
      "custom cutout stress ball",
      "EVA sensory ball manufacturer",
      "colorful squeeze ball OEM",
      "promotional stress ball custom",
      "party favor squeeze toys",
    ],
    images: images(
      "custom-eva-geometric-cutout-squeeze-ball",
      "/images/products/custom-eva-geometric-cutout-squeeze-ball/hero.webp",
    ),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "custom-jumbo-ghost-squishy",
    name: "Custom Jumbo Ghost Squishy",
    category: "Seasonal Squishy / OEM-ODM",
    tag: "Halloween Custom Design",
    note: "Original jumbo ghost slow-rise squishies for Halloween campaigns, party favors, seasonal retail and branded gift programs. Develop a buyer-approved ghost silhouette, face artwork, colors, logo placement, rebound feel and retail packaging without relying on licensed character artwork.",
    seoTitle: "Custom Jumbo Ghost Squishy Manufacturer",
    seoDescription: "Develop original jumbo ghost squishy toys with custom silhouette, facial artwork, slow-rise feel, logo, packaging and seasonal retail assortment options.",
    alt: "custom jumbo ghost squishy slow rise Halloween toy OEM manufacturer",
    keywords: [
      "custom ghost squishy",
      "jumbo Halloween squishy",
      "slow rise ghost toy manufacturer",
      "Halloween stress toy OEM",
      "custom party favor squishy",
      "seasonal squishy toy wholesale",
    ],
    images: images(
      "custom-jumbo-ghost-squishy",
      "/images/products/custom-jumbo-ghost-squishy/hero.png",
    ),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "crystal-clear-cat-paw-squishy",
    name: "Wholesale Crystal Clear Cat Paw Squishy",
    category: "Crystal Jelly Squishy · Wholesale",
    tag: "High Visual Appeal",
    note: "Ice-clear cat paw squishies with glitter bubbles, butterfly details and five bright color options. Designed for sensory retail, gift shops, online marketplaces and collectible assortments, with custom colors, inclusions and packaging available.",
    alt: "wholesale crystal clear cat paw squishy colorful transparent squeeze toys factory supplier",
    keywords: [
      "crystal clear cat paw squishy",
      "transparent paw squeeze toy wholesale",
      "ice clear squishy manufacturer",
      "cat paw sensory toy",
      "wholesale cute squishy toys",
      "custom jelly paw squishy",
    ],
    images: images(
      "crystal-clear-cat-paw-squishy",
      "/images/products/crystal-clear-cat-paw-squishy/hero.png",
    ),
    video: "/videos/crystal-clear-cat-paw-squishy.mp4",
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "glitter-bao-bun",
    name: "OEM Glitter Bao Bun Squishy",
    category: "Glitter Squishy · OEM/ODM",
    tag: "OEM Available",
    note: "Glitter steamer-bun squishy with strong shelf appeal for gift and impulse retail. OEM colors, faces and packaging for Amazon sellers and wholesale importers.",
    alt: "OEM glitter bao bun squishy wholesale Amazon seller retail custom design LINHAO China toy manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "ODM squishy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "retail toy wholesale",
      "glitter bao bun squishy OEM",
    ],
    images: images("glitter-bao-bun", "/images/products/glitter-bao-bun/hero.png"),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "glitter-basket-blue",
    name: "OEM Glitter Basket Squishy — Blue",
    category: "Glitter Squishy · Wholesale",
    tag: "Export Bestseller",
    note: "Slow-rise glitter basket — LINHAO's top export SKU with repeat orders. Custom color series and private label for Amazon FBA and distributors.",
    alt: "OEM blue glitter basket squishy export bestseller wholesale Amazon FBA LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale squishy toys",
      "Amazon FBA toys",
      "export squishy wholesale",
      "retail squishy supplier",
      "glitter basket squishy OEM",
    ],
    images: images("glitter-basket-blue", "/images/products/glitter-basket-blue/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "butter-stick",
    name: "OEM Butter Stick Food Squishy",
    category: "Food Squishy · OEM/ODM",
    tag: "Custom Color",
    note: "Viral food-trend stretch squishy with long-format recovery. Custom shapes and colors for Amazon sellers and promotional buyers.",
    alt: "OEM butter stick food squishy wholesale Amazon seller custom color LINHAO China supplier",
    keywords: [
      "OEM toy manufacturer",
      "ODM squishy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "food squishy OEM",
      "butter stick squishy wholesale",
    ],
    images: images("butter-stick", "/images/products/butter-stick/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "mini-animal-mix",
    name: "OEM Mini Animal Squishy Mix",
    category: "Mini Sensory · Wholesale",
    tag: "Blind Box Ready",
    note: "20+ mini designs for blind bags, party packs and vending. Custom mix and branded bags for Amazon and party favor wholesalers.",
    alt: "OEM mini animal squishy assortment blind box wholesale Amazon seller LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "blind box squishy wholesale",
      "retail party favor supplier",
      "mini squishy assortment OEM",
    ],
    images: images("mini-animal-mix", "/images/products/mini-animal-mix/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "halloween-shiny-bao",
    name: "OEM Halloween Shiny Bao Squishy",
    category: "Seasonal Squishy · OEM/ODM",
    tag: "Blind Box Ready",
    note: "Seasonal blind box line with 6 glitter baozi designs. Custom artwork and PDQ shippers for seasonal retail and Amazon sellers.",
    alt: "OEM Halloween shiny bao squishy blind box wholesale retail Amazon seller LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "halloween squishy OEM",
      "seasonal retail wholesale",
      "blind box baozi squishy wholesale",
    ],
    images: images("halloween-shiny-bao", "/images/products/halloween-shiny-bao/hero.png"),
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "pu-slow-rise-animal-keychain",
    name: "OEM PU Slow-Rise Animal Squishy Keychain Blind Box",
    category: "PU Slow-Rise Squishy · OEM/ODM",
    tag: "Blind Box Ready",
    note: "Colorful PU slow-rise animal squishy keychains with 20+ character directions for blind boxes, vending, party favors and collectible retail. Custom artwork, colors, assortments and packaging available.",
    alt: "OEM PU slow-rise animal squishy keychain blind box assortment custom wholesale manufacturer",
    keywords: [
      "PU slow rise squishy manufacturer",
      "custom squishy keychain",
      "animal squishy blind box",
      "OEM squishy keychain",
      "wholesale decompression toys",
      "custom animal squishy toys",
    ],
    images: images(
      "pu-slow-rise-animal-keychain",
      "/images/products/pu-slow-rise-animal-keychain/hero.png",
    ),
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "custom-pu-fruit-animal-figures",
    name: "Custom PU Slow-Rise Fruit & Animal Squishy Figures",
    category: "Custom Shape Squishy · OEM/ODM",
    tag: "Any Shape Custom",
    note: "Turn drawings, fruit ideas, animals, mascots or original characters into PU slow-rise squeeze figures. Shape, size, softness, color, face artwork, logo and retail packaging can be developed for your project.",
    alt: "custom PU slow-rise fruit animal squishy figures made from buyer artwork OEM manufacturer",
    keywords: [
      "custom PU squishy manufacturer",
      "custom shape slow rise toy",
      "fruit squishy custom",
      "animal PU figure OEM",
      "squishy toy from drawing",
      "custom decompression figure",
    ],
    images: images(
      "custom-pu-fruit-animal-figures",
      "/images/products/custom-pu-fruit-animal-figures/hero.png",
    ),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "long-leg-fuzzy-character-bag-charm",
    name: "Custom Long-Leg Fuzzy Character Bag Charm",
    category: "Plush Bag Charm · OEM/ODM",
    tag: "Store Bestseller",
    note: "Playful long-leg fuzzy characters designed for collectible bag charm programs, fashion accessories and impulse gifting. Customize the character face, fur color, footwear, hardware, logo tag and retail packaging.",
    alt: "custom long leg fuzzy character plush bag charm keychain wholesale manufacturer",
    keywords: [
      "long leg fuzzy bag charm",
      "custom plush character keychain",
      "wholesale fluffy bag charms",
      "OEM plush keychain manufacturer",
      "collectible bag charm supplier",
      "custom character accessories",
    ],
    images: images(
      "long-leg-fuzzy-character-bag-charm",
      "/images/products/long-leg-fuzzy-character-bag-charm/hero.jpg",
    ),
    featured: true,
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "mini-fuzzy-character-keychain",
    name: "Custom Mini Fuzzy Character Keychain",
    category: "Plush Keychain · Wholesale",
    tag: "High-Volume Style",
    note: "Compact fuzzy character keychains with expressive eyes and mixed fabric details for retail assortments and collectible drops. Private-label colors, accessories, hardware and branded cards are available.",
    alt: "custom mini fuzzy character plush keychain wholesale private label supplier",
    keywords: [
      "mini fuzzy character keychain",
      "wholesale plush keychains",
      "custom fluffy bag charm",
      "private label plush accessories",
      "collectible character charm",
      "OEM keychain manufacturer",
    ],
    images: images(
      "mini-fuzzy-character-keychain",
      "/images/products/mini-fuzzy-character-keychain/hero.jpg",
    ),
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "cherry-plush-bag-charm",
    name: "Custom Cherry Plush Bag Charm",
    category: "Fruit Bag Charm · OEM/ODM",
    tag: "Trend Pick",
    note: "Double-cherry plush bag charm with a soft tactile finish for fashion accessories, seasonal gifting and colorful retail collections. Customize fruit colors, leaf embroidery, size, hardware and packaging.",
    alt: "custom cherry plush bag charm fuzzy fruit keychain wholesale manufacturer",
    keywords: [
      "cherry plush bag charm",
      "fruit keychain wholesale",
      "custom fuzzy cherry charm",
      "OEM fruit plush keychain",
      "fashion bag accessory supplier",
      "private label bag charms",
    ],
    images: images(
      "cherry-plush-bag-charm",
      "/images/products/cherry-plush-bag-charm/hero.jpg",
    ),
    featured: true,
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "bow-fuzzy-ball-bag-charm",
    name: "Custom Bow Fuzzy Ball Bag Charm",
    category: "Character Bag Charm · Wholesale",
    tag: "Collectible Ready",
    note: "A soft round character charm finished with an oversized bow for cute accessory collections and social-first product drops. Develop custom faces, bow patterns, colorways, logo labels and retail cards.",
    alt: "custom bow fuzzy ball character bag charm plush keychain wholesale supplier",
    keywords: [
      "bow fuzzy ball bag charm",
      "cute plush keychain wholesale",
      "custom character bag accessory",
      "collectible plush charm",
      "OEM fuzzy keychain",
      "private label bag charm",
    ],
    images: images(
      "bow-fuzzy-ball-bag-charm",
      "/images/products/bow-fuzzy-ball-bag-charm/hero.jpg",
    ),
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "tennis-ball-plush-keychain",
    name: "Custom Tennis Ball Plush Keychain",
    category: "Sports Bag Charm · OEM/ODM",
    tag: "Sports Trend",
    note: "Soft tennis-ball keychain for sports clubs, tournament merchandise, school gifts and lifestyle accessory ranges. Customize ball colors, embroidered logos, clips, straps and branded packaging.",
    alt: "custom tennis ball plush keychain sports bag charm wholesale manufacturer",
    keywords: [
      "tennis ball plush keychain",
      "sports bag charm wholesale",
      "custom tennis merchandise",
      "OEM plush sports keychain",
      "club promotional gifts",
      "custom logo ball charm",
    ],
    images: images(
      "tennis-ball-plush-keychain",
      "/images/products/tennis-ball-plush-keychain/hero.jpg",
    ),
    featured: true,
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "lucky-persimmon-plush-charm",
    name: "Custom Lucky Persimmon Plush Charm",
    category: "Fruit Gift Charm · OEM/ODM",
    tag: "Giftable Design",
    note: "Bright persimmon-inspired plush charm created for festive gifts, cultural collections and fruit-themed accessory programs. Customize the message tag, fruit color, leaf shape, hardware and gift packaging.",
    alt: "custom lucky persimmon plush charm fruit keychain wholesale supplier",
    keywords: [
      "persimmon plush charm",
      "fruit bag charm wholesale",
      "custom lucky gift keychain",
      "OEM plush fruit accessory",
      "festive promotional charm",
      "private label fruit keychain",
    ],
    images: images(
      "lucky-persimmon-plush-charm",
      "/images/products/lucky-persimmon-plush-charm/hero.jpg",
    ),
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "panda-needle-felting-kit",
    name: "Custom Panda Needle Felting DIY Kit",
    category: "Needle Felting Kit · OEM/ODM",
    tag: "6,500+ Sold Style",
    note: "Beginner-friendly panda needle felting kit for craft retail, gift boxes and creative workshops. Customize the animal design, wool colors, accessories, instruction language, tool set and branded packaging.",
    alt: "custom panda needle felting DIY kit wholesale craft supplier",
    keywords: ["panda needle felting kit", "DIY wool felt kit wholesale", "custom craft kit manufacturer", "beginner felting kit", "OEM needle felt animal kit", "creative gift kit supplier"],
    images: images("panda-needle-felting-kit", "/images/products/panda-needle-felting-kit/hero.jpg"),
    featured: true,
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "horse-success-embroidery-charm-kit",
    name: "Custom Horse Success Embroidery Charm Kit",
    category: "Embroidery Charm Kit · OEM/ODM",
    tag: "Giftable Craft",
    note: "Traditional horse-themed embroidery charm kit designed for seasonal gifting, cultural merchandise and mindful crafting. Customize the artwork, thread palette, tassel, charm hardware, instruction card and gift packaging.",
    alt: "custom horse success embroidery charm DIY kit wholesale",
    keywords: ["horse embroidery charm kit", "DIY embroidery kit wholesale", "custom Chinese charm kit", "hand embroidery gift kit", "OEM craft kit", "tassel charm DIY kit"],
    images: images("horse-success-embroidery-charm-kit", "/images/products/horse-success-embroidery-charm-kit/hero.jpg"),
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "capybara-needle-felting-kit",
    name: "Custom Capybara Needle Felting DIY Kit",
    category: "Needle Felting Kit · Wholesale",
    tag: "Trend Character",
    note: "Pocket-size capybara needle felting kit with a playful companion detail for trend-led craft assortments. Customize the character pose, wool colors, accessories, tools, multilingual instructions and retail box.",
    alt: "custom capybara needle felting DIY kit wholesale manufacturer",
    keywords: ["capybara needle felting kit", "capybara craft kit wholesale", "DIY wool felt animal", "custom felting kit", "trend character craft kit", "OEM hobby kit supplier"],
    images: images("capybara-needle-felting-kit", "/images/products/capybara-needle-felting-kit/hero.jpg"),
    featured: true,
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "capybara-crochet-keychain-kit",
    name: "Custom Capybara Crochet Keychain Kit",
    category: "Crochet Kit · OEM/ODM",
    tag: "6,300+ Sold Style",
    note: "Cute capybara crochet keychain kit for beginners, hobby retailers and social-commerce gift collections. Customize the yarn colors, companion accessory, keychain hardware, instruction language and branded kit packaging.",
    alt: "custom capybara crochet keychain DIY kit wholesale supplier",
    keywords: ["capybara crochet kit", "crochet keychain kit wholesale", "beginner amigurumi kit", "custom yarn craft kit", "OEM crochet animal kit", "DIY gift kit supplier"],
    images: images("capybara-crochet-keychain-kit", "/images/products/capybara-crochet-keychain-kit/hero.jpg"),
    featured: true,
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "peace-charm-embroidery-kit",
    name: "Custom Peace Charm Embroidery DIY Kit",
    category: "Embroidery Kit · Private Label",
    tag: "Cultural Gift",
    note: "Mountain-and-wave peace charm embroidery kit suited to mindful crafts, travel gifts and cultural retail. Customize the motif, colors, wording, tassel, backing fabric, instruction card and presentation box.",
    alt: "custom peace charm embroidery DIY kit private label wholesale",
    keywords: ["peace charm embroidery kit", "DIY embroidery charm wholesale", "custom cultural craft kit", "mountain wave embroidery", "private label embroidery kit", "mindful craft gift"],
    images: images("peace-charm-embroidery-kit", "/images/products/peace-charm-embroidery-kit/hero.jpg"),
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "field-landscape-needle-felt-art-kit",
    name: "Custom Field Landscape Needle Felt Art Kit",
    category: "Felt Painting Kit · OEM/ODM",
    tag: "Amazon-Ready",
    note: "Colorful hoop-mounted landscape needle felting kit for adult crafts, home décor and creative gifting. Customize the scenery, hoop size, wool palette, English instructions, tool configuration and marketplace packaging.",
    alt: "custom field landscape needle felt painting DIY kit wholesale",
    keywords: ["landscape needle felting kit", "felt painting kit wholesale", "adult DIY craft kit", "custom wool felt art", "Amazon craft kit supplier", "OEM needle felting picture kit"],
    images: images("field-landscape-needle-felt-art-kit", "/images/products/field-landscape-needle-felt-art-kit/hero.jpg"),
    featured: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "comfort-cat-plush",
    name: "OEM Comfort Cat Plush Toy",
    category: "Emotional Plush · OEM/ODM",
    tag: "Custom Color",
    note: "Soft emotional plush with expressive face for gifting and desk décor. Character and packaging OEM for gift brands and Amazon sellers.",
    alt: "OEM comfort cat plush toy wholesale Amazon seller emotional gift LINHAO China manufacturer",
    keywords: [
      "OEM plush manufacturer",
      "ODM plush toys",
      "wholesale plush toys",
      "Amazon seller plush",
      "retail gift wholesale",
      "emotional plush OEM",
    ],
    images: images("comfort-cat-plush", "/images/real-products/green-cat-plush.jpg"),
    filterGroup: "emotional-gifts",
  },
  {
    slug: "mood-bunny-plush",
    name: "OEM Long-Ear Mood Bunny Plush",
    category: "Emotional Plush · Wholesale",
    tag: "OEM Available",
    note: "Long-ear mood character for collectible series and mascot IP. Expression variants for retailers and private label programs.",
    alt: "OEM mood bunny plush character series wholesale Amazon seller LINHAO China manufacturer",
    keywords: [
      "OEM plush manufacturer",
      "wholesale plush toys",
      "Amazon seller plush",
      "character plush OEM",
      "retail collectible wholesale",
      "ODM plush manufacturer",
    ],
    images: images("mood-bunny-plush", "/images/real-products/emotion-bunny-plush.jpg"),
    filterGroup: "emotional-gifts",
  },
  {
    slug: "flower-bag-charm",
    name: "OEM Flower Plush Bag Charm",
    category: "Bag Accessories · OEM/ODM",
    tag: "Custom Packaging",
    note: "Lightweight flower clip-on with keyring for bag charm programs. Custom styles and retail cards for accessory brands and Amazon sellers.",
    alt: "OEM flower plush bag charm wholesale Amazon seller keychain accessory LINHAO China supplier",
    keywords: [
      "OEM toy manufacturer",
      "wholesale bag charms",
      "Amazon seller accessories",
      "plush keychain OEM",
      "retail gift wholesale",
      "ODM accessory manufacturer",
    ],
    images: images("flower-bag-charm", "/images/real-products/flower-bag-charm.jpg"),
    filterGroup: "bag-charms",
  },
  {
    slug: "mini-kitty-desk-buddy",
    name: "OEM Mini Kitty Desk Buddy Plush",
    category: "Desk Companion · Wholesale",
    tag: "OEM Available",
    note: "Mini cat desk display for collectible impulse sets. 6–12 SKU series with display trays for gift shops and Amazon sellers.",
    alt: "OEM mini kitty desk buddy plush wholesale Amazon seller collectible LINHAO China manufacturer",
    keywords: [
      "OEM plush manufacturer",
      "wholesale plush toys",
      "Amazon seller toys",
      "desk companion plush OEM",
      "retail collectible wholesale",
      "ODM plush manufacturer",
    ],
    images: images("mini-kitty-desk-buddy", "/images/real-products/mini-kitty-chair.jpg"),
    filterGroup: "plush",
  },
  {
    slug: "light-up-robot",
    name: "OEM Light-Up Robot Gift Toy",
    category: "Interactive Gift · OEM/ODM",
    tag: "Custom Color",
    note: "LED light and movement for higher gift perceived value. Custom shapes and branded boxes for promo distributors and retail chains.",
    alt: "OEM light up robot toy wholesale Amazon seller promotional gift LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale gift toys",
      "Amazon seller toys",
      "light up toy OEM",
      "promotional toy wholesale",
      "retail novelty supplier",
    ],
    images: images("light-up-robot", "/images/real-products/light-up-robot.jpg"),
    filterGroup: "emotional-gifts",
  },
  {
    slug: "custom-gift-set",
    name: "OEM Custom Retail Gift Set",
    category: "OEM / ODM · Turnkey",
    tag: "OEM Available",
    note: "Turnkey squishy, plush, accessory and packaging in one program. Private label collections for brand owners and Amazon wholesale buyers.",
    alt: "OEM custom retail gift set private label wholesale Amazon seller LINHAO China toy manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "ODM toy manufacturer",
      "wholesale gift sets",
      "Amazon private label toys",
      "retail toy wholesale",
      "turnkey OEM toy supplier",
    ],
    images: images("custom-gift-set", "/images/real-products/catalog-hero.jpg"),
    filterGroup: "oem",
  },
];