export type ProductFilterGroup =
  | "squishy"
  | "plush"
  | "bag-charms"
  | "diy-crafts"
  | "emotional-gifts"
  | "oem";

export type ProductImageSet = {
  hero: string;
  detail?: string;
  packaging?: string;
  oemCase?: string;
};

export type Product = {
  slug: string;
  name: string;
  category: string;
  tag: string;
  note: string;
  alt: string;
  keywords: string[];
  images: ProductImageSet;
  video?: string;
  featured?: boolean;
  bestseller?: boolean;
  filterGroup: ProductFilterGroup;
};

function images(slug: string, hero: string): ProductImageSet {
  return {
    hero,
    detail: `/images/products/${slug}/detail.png`,
    packaging: `/images/products/${slug}/packaging.png`,
    oemCase: `/images/products/${slug}/oem-case.png`,
  };
}

export const products: Product[] = [
  {
    slug: "dumpling-squishy-blind-box",
    name: "Custom Dumpling Squishy Blind Box Series",
    category: "Viral Squishy · OEM/ODM",
    tag: "2026 Trend Pick",
    note: "Pastel dumpling and bao bun squishies developed as blind-box assortments for collectible retail and social-commerce launches. Customize expressions, colorways, softness, scent, rarity mix and display packaging.",
    alt: "custom dumpling squishy blind box bao bun sensory toys wholesale manufacturer",
    keywords: [
      "dumpling squishy manufacturer",
      "bao bun squishy wholesale",
      "squishy blind box OEM",
      "custom sensory toy supplier",
      "kawaii dumpling squishy",
      "private label squishy toys",
    ],
    images: images("dumpling-squishy-blind-box", "/images/products/dumpling-squishy-blind-box/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "transparent-gel-cube-squishy",
    name: "Custom Transparent Gel Cube Sensory Squishy",
    category: "Sensory Stress Cube · Wholesale",
    tag: "High Search Interest",
    note: "Clear rounded sensory cubes with colorful transparent finishes and optional glitter effects for tactile, desk and gift assortments. Customize dimensions, firmness, color, inclusions and retail packaging after material review.",
    alt: "custom transparent gel cube squishy sensory stress cube wholesale supplier",
    keywords: [
      "gel cube squishy",
      "sensory stress cube wholesale",
      "clear squishy cube manufacturer",
      "custom stress relief toys",
      "transparent sensory toy",
      "bulk squishy cubes",
    ],
    images: images("transparent-gel-cube-squishy", "/images/products/transparent-gel-cube-squishy/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "capybara-squishy-assortment",
    name: "Custom Capybara Squishy Assortment",
    category: "Character Squishy · OEM/ODM",
    tag: "Viral Character",
    note: "Original capybara squeeze characters with accessory variations for collectible assortments, impulse gifting and key retail moments. Customize poses, accessories, colors, material feel, packaging and assortment ratios.",
    alt: "custom capybara squishy stress toy assortment wholesale OEM manufacturer",
    keywords: [
      "capybara squishy",
      "capybara stress toy wholesale",
      "custom animal squishy manufacturer",
      "capybara sensory toy",
      "OEM character squishy",
      "bulk capybara toys",
    ],
    images: images("capybara-squishy-assortment", "/images/products/capybara-squishy-assortment/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "soft-sticky-squishy-assortment",
    name: "Custom Soft Sticky Squishy Assortment",
    category: "Taba-Style Squishy · OEM/ODM",
    tag: "Social Trend",
    note: "Ultra-soft fruit and animal squeeze shapes created for trend-led sensory collections. Develop original shapes with custom surface feel, color, print, firmness, dust-control packaging and private-label presentation.",
    alt: "custom soft sticky taba style squishy assortment wholesale manufacturer",
    keywords: [
      "taba squishy manufacturer",
      "soft sticky squishy wholesale",
      "custom TPR squishy toy",
      "fruit squishy assortment",
      "private label sensory toys",
      "OEM soft squishy supplier",
    ],
    images: images("soft-sticky-squishy-assortment", "/images/products/soft-sticky-squishy-assortment/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "bakery-slow-rise-squishy-assortment",
    name: "Custom Bakery Slow-Rise Squishy Assortment",
    category: "Food Squishy · Wholesale",
    tag: "Evergreen Seller",
    note: "Croissant, toast, roll, waffle, cake and cream-bun slow-rise toys for food-themed retail and gift programs. Customize bakery shapes, recovery speed, scent, faces, colorways and branded packaging.",
    alt: "custom bakery food slow rise squishy toys wholesale manufacturer",
    keywords: [
      "food squishy wholesale",
      "slow rise squishy manufacturer",
      "bread squishy toys bulk",
      "bakery squishy assortment",
      "scented squishy OEM",
      "custom dessert squishy",
    ],
    images: images("bakery-slow-rise-squishy-assortment", "/images/products/bakery-slow-rise-squishy-assortment/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "adult-desk-sensory-squishy",
    name: "Custom Adult Desk Sensory Squishy",
    category: "Quiet Desk Sensory · Private Label",
    tag: "Kidult Market",
    note: "Minimal pebble-shaped squeeze pieces designed for quiet desk, lifestyle gift and adult sensory collections. Customize form, resistance, color palette, surface finish, gift box and corporate branding without medical claims.",
    alt: "custom adult desk sensory squishy quiet stress relief toy wholesale",
    keywords: [
      "adult stress relief toy",
      "quiet desk sensory toy",
      "custom desk squishy",
      "private label stress toys",
      "adult sensory product wholesale",
      "OEM squeeze toy manufacturer",
    ],
    images: images("adult-desk-sensory-squishy", "/images/products/adult-desk-sensory-squishy/hero.png"),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "crystal-clear-cat-paw-squishy",
    name: "Wholesale Crystal Clear Cat Paw Squishy",
    category: "Crystal Jelly Squishy · Wholesale",
    tag: "High Visual Appeal",
    note: "Ice-clear cat paw squishies with glitter bubbles, butterfly details and five bright color options. Designed for sensory retail, gift shops, online marketplaces and collectible assortments, with custom colors, inclusions and packaging available.",
    alt: "wholesale crystal clear cat paw squishy colorful transparent squeeze toys factory supplier",
    keywords: [
      "crystal clear cat paw squishy",
      "transparent paw squeeze toy wholesale",
      "ice clear squishy manufacturer",
      "cat paw sensory toy",
      "wholesale cute squishy toys",
      "custom jelly paw squishy",
    ],
    images: images(
      "crystal-clear-cat-paw-squishy",
      "/images/products/crystal-clear-cat-paw-squishy/hero.png",
    ),
    video: "/videos/crystal-clear-cat-paw-squishy.mp4",
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "glitter-bao-bun",
    name: "OEM Glitter Bao Bun Squishy",
    category: "Glitter Squishy · OEM/ODM",
    tag: "OEM Available",
    note: "Glitter steamer-bun squishy with strong shelf appeal for gift and impulse retail. OEM colors, faces and packaging for Amazon sellers and wholesale importers.",
    alt: "OEM glitter bao bun squishy wholesale Amazon seller retail custom design LINHAO China toy manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "ODM squishy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "retail toy wholesale",
      "glitter bao bun squishy OEM",
    ],
    images: images("glitter-bao-bun", "/images/products/glitter-bao-bun/hero.png"),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "glitter-basket-blue",
    name: "OEM Glitter Basket Squishy — Blue",
    category: "Glitter Squishy · Wholesale",
    tag: "Export Bestseller",
    note: "Slow-rise glitter basket — LINHAO's top export SKU with repeat orders. Custom color series and private label for Amazon FBA and distributors.",
    alt: "OEM blue glitter basket squishy export bestseller wholesale Amazon FBA LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale squishy toys",
      "Amazon FBA toys",
      "export squishy wholesale",
      "retail squishy supplier",
      "glitter basket squishy OEM",
    ],
    images: images("glitter-basket-blue", "/images/products/glitter-basket-blue/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "butter-stick",
    name: "OEM Butter Stick Food Squishy",
    category: "Food Squishy · OEM/ODM",
    tag: "Custom Color",
    note: "Viral food-trend stretch squishy with long-format recovery. Custom shapes and colors for Amazon sellers and promotional buyers.",
    alt: "OEM butter stick food squishy wholesale Amazon seller custom color LINHAO China supplier",
    keywords: [
      "OEM toy manufacturer",
      "ODM squishy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "food squishy OEM",
      "butter stick squishy wholesale",
    ],
    images: images("butter-stick", "/images/products/butter-stick/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "mini-animal-mix",
    name: "OEM Mini Animal Squishy Mix",
    category: "Mini Sensory · Wholesale",
    tag: "Blind Box Ready",
    note: "20+ mini designs for blind bags, party packs and vending. Custom mix and branded bags for Amazon and party favor wholesalers.",
    alt: "OEM mini animal squishy assortment blind box wholesale Amazon seller LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "blind box squishy wholesale",
      "retail party favor supplier",
      "mini squishy assortment OEM",
    ],
    images: images("mini-animal-mix", "/images/products/mini-animal-mix/hero.png"),
    featured: true,
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "halloween-shiny-bao",
    name: "OEM Halloween Shiny Bao Squishy",
    category: "Seasonal Squishy · OEM/ODM",
    tag: "Blind Box Ready",
    note: "Seasonal blind box line with 6 glitter baozi designs. Custom artwork and PDQ shippers for seasonal retail and Amazon sellers.",
    alt: "OEM Halloween shiny bao squishy blind box wholesale retail Amazon seller LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale squishy toys",
      "Amazon seller toys",
      "halloween squishy OEM",
      "seasonal retail wholesale",
      "blind box baozi squishy wholesale",
    ],
    images: images("halloween-shiny-bao", "/images/products/halloween-shiny-bao/hero.png"),
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "pu-slow-rise-animal-keychain",
    name: "OEM PU Slow-Rise Animal Squishy Keychain Blind Box",
    category: "PU Slow-Rise Squishy · OEM/ODM",
    tag: "Blind Box Ready",
    note: "Colorful PU slow-rise animal squishy keychains with 20+ character directions for blind boxes, vending, party favors and collectible retail. Custom artwork, colors, assortments and packaging available.",
    alt: "OEM PU slow-rise animal squishy keychain blind box assortment custom wholesale manufacturer",
    keywords: [
      "PU slow rise squishy manufacturer",
      "custom squishy keychain",
      "animal squishy blind box",
      "OEM squishy keychain",
      "wholesale decompression toys",
      "custom animal squishy toys",
    ],
    images: images(
      "pu-slow-rise-animal-keychain",
      "/images/products/pu-slow-rise-animal-keychain/hero.png",
    ),
    bestseller: true,
    filterGroup: "squishy",
  },
  {
    slug: "custom-pu-fruit-animal-figures",
    name: "Custom PU Slow-Rise Fruit & Animal Squishy Figures",
    category: "Custom Shape Squishy · OEM/ODM",
    tag: "Any Shape Custom",
    note: "Turn drawings, fruit ideas, animals, mascots or original characters into PU slow-rise squeeze figures. Shape, size, softness, color, face artwork, logo and retail packaging can be developed for your project.",
    alt: "custom PU slow-rise fruit animal squishy figures made from buyer artwork OEM manufacturer",
    keywords: [
      "custom PU squishy manufacturer",
      "custom shape slow rise toy",
      "fruit squishy custom",
      "animal PU figure OEM",
      "squishy toy from drawing",
      "custom decompression figure",
    ],
    images: images(
      "custom-pu-fruit-animal-figures",
      "/images/products/custom-pu-fruit-animal-figures/hero.png",
    ),
    featured: true,
    filterGroup: "squishy",
  },
  {
    slug: "long-leg-fuzzy-character-bag-charm",
    name: "Custom Long-Leg Fuzzy Character Bag Charm",
    category: "Plush Bag Charm · OEM/ODM",
    tag: "Store Bestseller",
    note: "Playful long-leg fuzzy characters designed for collectible bag charm programs, fashion accessories and impulse gifting. Customize the character face, fur color, footwear, hardware, logo tag and retail packaging.",
    alt: "custom long leg fuzzy character plush bag charm keychain wholesale manufacturer",
    keywords: [
      "long leg fuzzy bag charm",
      "custom plush character keychain",
      "wholesale fluffy bag charms",
      "OEM plush keychain manufacturer",
      "collectible bag charm supplier",
      "custom character accessories",
    ],
    images: images(
      "long-leg-fuzzy-character-bag-charm",
      "/images/products/long-leg-fuzzy-character-bag-charm/hero.jpg",
    ),
    featured: true,
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "mini-fuzzy-character-keychain",
    name: "Custom Mini Fuzzy Character Keychain",
    category: "Plush Keychain · Wholesale",
    tag: "High-Volume Style",
    note: "Compact fuzzy character keychains with expressive eyes and mixed fabric details for retail assortments and collectible drops. Private-label colors, accessories, hardware and branded cards are available.",
    alt: "custom mini fuzzy character plush keychain wholesale private label supplier",
    keywords: [
      "mini fuzzy character keychain",
      "wholesale plush keychains",
      "custom fluffy bag charm",
      "private label plush accessories",
      "collectible character charm",
      "OEM keychain manufacturer",
    ],
    images: images(
      "mini-fuzzy-character-keychain",
      "/images/products/mini-fuzzy-character-keychain/hero.jpg",
    ),
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "cherry-plush-bag-charm",
    name: "Custom Cherry Plush Bag Charm",
    category: "Fruit Bag Charm · OEM/ODM",
    tag: "Trend Pick",
    note: "Double-cherry plush bag charm with a soft tactile finish for fashion accessories, seasonal gifting and colorful retail collections. Customize fruit colors, leaf embroidery, size, hardware and packaging.",
    alt: "custom cherry plush bag charm fuzzy fruit keychain wholesale manufacturer",
    keywords: [
      "cherry plush bag charm",
      "fruit keychain wholesale",
      "custom fuzzy cherry charm",
      "OEM fruit plush keychain",
      "fashion bag accessory supplier",
      "private label bag charms",
    ],
    images: images(
      "cherry-plush-bag-charm",
      "/images/products/cherry-plush-bag-charm/hero.jpg",
    ),
    featured: true,
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "bow-fuzzy-ball-bag-charm",
    name: "Custom Bow Fuzzy Ball Bag Charm",
    category: "Character Bag Charm · Wholesale",
    tag: "Collectible Ready",
    note: "A soft round character charm finished with an oversized bow for cute accessory collections and social-first product drops. Develop custom faces, bow patterns, colorways, logo labels and retail cards.",
    alt: "custom bow fuzzy ball character bag charm plush keychain wholesale supplier",
    keywords: [
      "bow fuzzy ball bag charm",
      "cute plush keychain wholesale",
      "custom character bag accessory",
      "collectible plush charm",
      "OEM fuzzy keychain",
      "private label bag charm",
    ],
    images: images(
      "bow-fuzzy-ball-bag-charm",
      "/images/products/bow-fuzzy-ball-bag-charm/hero.jpg",
    ),
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "tennis-ball-plush-keychain",
    name: "Custom Tennis Ball Plush Keychain",
    category: "Sports Bag Charm · OEM/ODM",
    tag: "Sports Trend",
    note: "Soft tennis-ball keychain for sports clubs, tournament merchandise, school gifts and lifestyle accessory ranges. Customize ball colors, embroidered logos, clips, straps and branded packaging.",
    alt: "custom tennis ball plush keychain sports bag charm wholesale manufacturer",
    keywords: [
      "tennis ball plush keychain",
      "sports bag charm wholesale",
      "custom tennis merchandise",
      "OEM plush sports keychain",
      "club promotional gifts",
      "custom logo ball charm",
    ],
    images: images(
      "tennis-ball-plush-keychain",
      "/images/products/tennis-ball-plush-keychain/hero.jpg",
    ),
    featured: true,
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "lucky-persimmon-plush-charm",
    name: "Custom Lucky Persimmon Plush Charm",
    category: "Fruit Gift Charm · OEM/ODM",
    tag: "Giftable Design",
    note: "Bright persimmon-inspired plush charm created for festive gifts, cultural collections and fruit-themed accessory programs. Customize the message tag, fruit color, leaf shape, hardware and gift packaging.",
    alt: "custom lucky persimmon plush charm fruit keychain wholesale supplier",
    keywords: [
      "persimmon plush charm",
      "fruit bag charm wholesale",
      "custom lucky gift keychain",
      "OEM plush fruit accessory",
      "festive promotional charm",
      "private label fruit keychain",
    ],
    images: images(
      "lucky-persimmon-plush-charm",
      "/images/products/lucky-persimmon-plush-charm/hero.jpg",
    ),
    bestseller: true,
    filterGroup: "bag-charms",
  },
  {
    slug: "panda-needle-felting-kit",
    name: "Custom Panda Needle Felting DIY Kit",
    category: "Needle Felting Kit · OEM/ODM",
    tag: "6,500+ Sold Style",
    note: "Beginner-friendly panda needle felting kit for craft retail, gift boxes and creative workshops. Customize the animal design, wool colors, accessories, instruction language, tool set and branded packaging.",
    alt: "custom panda needle felting DIY kit wholesale craft supplier",
    keywords: ["panda needle felting kit", "DIY wool felt kit wholesale", "custom craft kit manufacturer", "beginner felting kit", "OEM needle felt animal kit", "creative gift kit supplier"],
    images: images("panda-needle-felting-kit", "/images/products/panda-needle-felting-kit/hero.jpg"),
    featured: true,
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "horse-success-embroidery-charm-kit",
    name: "Custom Horse Success Embroidery Charm Kit",
    category: "Embroidery Charm Kit · OEM/ODM",
    tag: "Giftable Craft",
    note: "Traditional horse-themed embroidery charm kit designed for seasonal gifting, cultural merchandise and mindful crafting. Customize the artwork, thread palette, tassel, charm hardware, instruction card and gift packaging.",
    alt: "custom horse success embroidery charm DIY kit wholesale",
    keywords: ["horse embroidery charm kit", "DIY embroidery kit wholesale", "custom Chinese charm kit", "hand embroidery gift kit", "OEM craft kit", "tassel charm DIY kit"],
    images: images("horse-success-embroidery-charm-kit", "/images/products/horse-success-embroidery-charm-kit/hero.jpg"),
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "capybara-needle-felting-kit",
    name: "Custom Capybara Needle Felting DIY Kit",
    category: "Needle Felting Kit · Wholesale",
    tag: "Trend Character",
    note: "Pocket-size capybara needle felting kit with a playful companion detail for trend-led craft assortments. Customize the character pose, wool colors, accessories, tools, multilingual instructions and retail box.",
    alt: "custom capybara needle felting DIY kit wholesale manufacturer",
    keywords: ["capybara needle felting kit", "capybara craft kit wholesale", "DIY wool felt animal", "custom felting kit", "trend character craft kit", "OEM hobby kit supplier"],
    images: images("capybara-needle-felting-kit", "/images/products/capybara-needle-felting-kit/hero.jpg"),
    featured: true,
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "capybara-crochet-keychain-kit",
    name: "Custom Capybara Crochet Keychain Kit",
    category: "Crochet Kit · OEM/ODM",
    tag: "6,300+ Sold Style",
    note: "Cute capybara crochet keychain kit for beginners, hobby retailers and social-commerce gift collections. Customize the yarn colors, companion accessory, keychain hardware, instruction language and branded kit packaging.",
    alt: "custom capybara crochet keychain DIY kit wholesale supplier",
    keywords: ["capybara crochet kit", "crochet keychain kit wholesale", "beginner amigurumi kit", "custom yarn craft kit", "OEM crochet animal kit", "DIY gift kit supplier"],
    images: images("capybara-crochet-keychain-kit", "/images/products/capybara-crochet-keychain-kit/hero.jpg"),
    featured: true,
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "peace-charm-embroidery-kit",
    name: "Custom Peace Charm Embroidery DIY Kit",
    category: "Embroidery Kit · Private Label",
    tag: "Cultural Gift",
    note: "Mountain-and-wave peace charm embroidery kit suited to mindful crafts, travel gifts and cultural retail. Customize the motif, colors, wording, tassel, backing fabric, instruction card and presentation box.",
    alt: "custom peace charm embroidery DIY kit private label wholesale",
    keywords: ["peace charm embroidery kit", "DIY embroidery charm wholesale", "custom cultural craft kit", "mountain wave embroidery", "private label embroidery kit", "mindful craft gift"],
    images: images("peace-charm-embroidery-kit", "/images/products/peace-charm-embroidery-kit/hero.jpg"),
    bestseller: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "field-landscape-needle-felt-art-kit",
    name: "Custom Field Landscape Needle Felt Art Kit",
    category: "Felt Painting Kit · OEM/ODM",
    tag: "Amazon-Ready",
    note: "Colorful hoop-mounted landscape needle felting kit for adult crafts, home décor and creative gifting. Customize the scenery, hoop size, wool palette, English instructions, tool configuration and marketplace packaging.",
    alt: "custom field landscape needle felt painting DIY kit wholesale",
    keywords: ["landscape needle felting kit", "felt painting kit wholesale", "adult DIY craft kit", "custom wool felt art", "Amazon craft kit supplier", "OEM needle felting picture kit"],
    images: images("field-landscape-needle-felt-art-kit", "/images/products/field-landscape-needle-felt-art-kit/hero.jpg"),
    featured: true,
    filterGroup: "diy-crafts",
  },
  {
    slug: "comfort-cat-plush",
    name: "OEM Comfort Cat Plush Toy",
    category: "Emotional Plush · OEM/ODM",
    tag: "Custom Color",
    note: "Soft emotional plush with expressive face for gifting and desk décor. Character and packaging OEM for gift brands and Amazon sellers.",
    alt: "OEM comfort cat plush toy wholesale Amazon seller emotional gift LINHAO China manufacturer",
    keywords: [
      "OEM plush manufacturer",
      "ODM plush toys",
      "wholesale plush toys",
      "Amazon seller plush",
      "retail gift wholesale",
      "emotional plush OEM",
    ],
    images: images("comfort-cat-plush", "/images/real-products/green-cat-plush.jpg"),
    filterGroup: "emotional-gifts",
  },
  {
    slug: "mood-bunny-plush",
    name: "OEM Long-Ear Mood Bunny Plush",
    category: "Emotional Plush · Wholesale",
    tag: "OEM Available",
    note: "Long-ear mood character for collectible series and mascot IP. Expression variants for retailers and private label programs.",
    alt: "OEM mood bunny plush character series wholesale Amazon seller LINHAO China manufacturer",
    keywords: [
      "OEM plush manufacturer",
      "wholesale plush toys",
      "Amazon seller plush",
      "character plush OEM",
      "retail collectible wholesale",
      "ODM plush manufacturer",
    ],
    images: images("mood-bunny-plush", "/images/real-products/emotion-bunny-plush.jpg"),
    filterGroup: "emotional-gifts",
  },
  {
    slug: "flower-bag-charm",
    name: "OEM Flower Plush Bag Charm",
    category: "Bag Accessories · OEM/ODM",
    tag: "Custom Packaging",
    note: "Lightweight flower clip-on with keyring for bag charm programs. Custom styles and retail cards for accessory brands and Amazon sellers.",
    alt: "OEM flower plush bag charm wholesale Amazon seller keychain accessory LINHAO China supplier",
    keywords: [
      "OEM toy manufacturer",
      "wholesale bag charms",
      "Amazon seller accessories",
      "plush keychain OEM",
      "retail gift wholesale",
      "ODM accessory manufacturer",
    ],
    images: images("flower-bag-charm", "/images/real-products/flower-bag-charm.jpg"),
    filterGroup: "bag-charms",
  },
  {
    slug: "mini-kitty-desk-buddy",
    name: "OEM Mini Kitty Desk Buddy Plush",
    category: "Desk Companion · Wholesale",
    tag: "OEM Available",
    note: "Mini cat desk display for collectible impulse sets. 6–12 SKU series with display trays for gift shops and Amazon sellers.",
    alt: "OEM mini kitty desk buddy plush wholesale Amazon seller collectible LINHAO China manufacturer",
    keywords: [
      "OEM plush manufacturer",
      "wholesale plush toys",
      "Amazon seller toys",
      "desk companion plush OEM",
      "retail collectible wholesale",
      "ODM plush manufacturer",
    ],
    images: images("mini-kitty-desk-buddy", "/images/real-products/mini-kitty-chair.jpg"),
    filterGroup: "plush",
  },
  {
    slug: "light-up-robot",
    name: "OEM Light-Up Robot Gift Toy",
    category: "Interactive Gift · OEM/ODM",
    tag: "Custom Color",
    note: "LED light and movement for higher gift perceived value. Custom shapes and branded boxes for promo distributors and retail chains.",
    alt: "OEM light up robot toy wholesale Amazon seller promotional gift LINHAO China manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "wholesale gift toys",
      "Amazon seller toys",
      "light up toy OEM",
      "promotional toy wholesale",
      "retail novelty supplier",
    ],
    images: images("light-up-robot", "/images/real-products/light-up-robot.jpg"),
    filterGroup: "emotional-gifts",
  },
  {
    slug: "custom-gift-set",
    name: "OEM Custom Retail Gift Set",
    category: "OEM / ODM · Turnkey",
    tag: "OEM Available",
    note: "Turnkey squishy, plush, accessory and packaging in one program. Private label collections for brand owners and Amazon wholesale buyers.",
    alt: "OEM custom retail gift set private label wholesale Amazon seller LINHAO China toy manufacturer",
    keywords: [
      "OEM toy manufacturer",
      "ODM toy manufacturer",
      "wholesale gift sets",
      "Amazon private label toys",
      "retail toy wholesale",
      "turnkey OEM toy supplier",
    ],
    images: images("custom-gift-set", "/images/real-products/catalog-hero.jpg"),
    filterGroup: "oem",
  },
];
